name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run yarn install
        run: yarn install --non-interactive
      - name: Run yarn lint:js
        run: yarn lint:js
      - name: Run yarn lint:hbs
        run: yarn lint:hbs

  test-ember:
    name: Tests / Ember
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run yarn install
        run: yarn install --non-interactive
      - name: Run yarn test
        run: yarn test

  test-node:
    name: Tests / Node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run yarn install
        run: yarn install --non-interactive
      - name: Run yarn node-test
        uses: paambaati/codeclimate-action@v2.5.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn node-test

  test-float:
    name: Tests / floating dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run yarn install
        run: yarn install --ignore-lockfile --non-interactive
      - name: Run yarn test
        run: yarn test

  try-scenarios:
    name: Tests / ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    needs: [lint, test-ember]

    strategy:
      matrix:
        ember-try-scenario:
          - ember-lts-3.8
          - ember-lts-3.12
          - ember-release
          - ember-beta
          - ember-canary
          - ember-default-with-jquery
          - ember-classic

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Run yarn install
        run: yarn install --non-interactive
      - name: Run yarn test:one
        env:
          EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
        run: yarn test:one $EMBER_TRY_SCENARIO
