name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

env:
  CI: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set environment ADDON_DOCS_VERSION_PATH
        run: echo "::set-env name=ADDON_DOCS_VERSION_PATH::${GITHUB_REF##*/}"
      - name: Set environment ADDON_DOCS_UPDATE_LATEST
        if: contains(github.ref , 'master') != true
        run: echo "::set-env name=ADDON_DOCS_UPDATE_LATEST::true"
      - name: Run yarn install --non-interactive
        run: yarn install
      - name: Run yarn deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: yarn deploy
